/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.siu.saku.jooq.tables.SakuPreRegister;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>ganxu</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SAKU_PRE_REGISTER_PKEY = Indexes0.SAKU_PRE_REGISTER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SAKU_PRE_REGISTER_PKEY = Internal.createIndex("saku_pre_register_pkey", SakuPreRegister.SAKU_PRE_REGISTER, new OrderField[] { SakuPreRegister.SAKU_PRE_REGISTER.ID }, true);
    }
}
