/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq;


import org.siu.saku.jooq.tables.SakuPreRegister;
import org.siu.saku.jooq.tables.SakuShorturlMap;
import org.siu.saku.jooq.tables.SakuUrlMap;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ganxu
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ganxu.saku_pre_register</code>.
     */
    public static final SakuPreRegister SAKU_PRE_REGISTER = SakuPreRegister.SAKU_PRE_REGISTER;

    /**
     * The table <code>ganxu.saku_shorturl_map</code>.
     */
    public static final SakuShorturlMap SAKU_SHORTURL_MAP = SakuShorturlMap.SAKU_SHORTURL_MAP;

    /**
     * The table <code>ganxu.saku_url_map</code>.
     */
    public static final SakuUrlMap SAKU_URL_MAP = SakuUrlMap.SAKU_URL_MAP;
}
