/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.siu.saku.jooq.tables.SakuUrlMap;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SakuUrlMapRecord extends TableRecordImpl<SakuUrlMapRecord> implements Record4<Long, String, String, Timestamp> {

    private static final long serialVersionUID = -739152176;

    /**
     * Setter for <code>ganxu.saku_url_map.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ganxu.saku_url_map.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ganxu.saku_url_map.l_url</code>. 长链
     */
    public void setLUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ganxu.saku_url_map.l_url</code>. 长链
     */
    public String getLUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ganxu.saku_url_map.s_url</code>. 短链
     */
    public void setSUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ganxu.saku_url_map.s_url</code>. 短链
     */
    public String getSUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ganxu.saku_url_map.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ganxu.saku_url_map.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SakuUrlMap.SAKU_URL_MAP.ID;
    }

    @Override
    public Field<String> field2() {
        return SakuUrlMap.SAKU_URL_MAP.L_URL;
    }

    @Override
    public Field<String> field3() {
        return SakuUrlMap.SAKU_URL_MAP.S_URL;
    }

    @Override
    public Field<Timestamp> field4() {
        return SakuUrlMap.SAKU_URL_MAP.CREATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLUrl();
    }

    @Override
    public String component3() {
        return getSUrl();
    }

    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLUrl();
    }

    @Override
    public String value3() {
        return getSUrl();
    }

    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    @Override
    public SakuUrlMapRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SakuUrlMapRecord value2(String value) {
        setLUrl(value);
        return this;
    }

    @Override
    public SakuUrlMapRecord value3(String value) {
        setSUrl(value);
        return this;
    }

    @Override
    public SakuUrlMapRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SakuUrlMapRecord values(Long value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SakuUrlMapRecord
     */
    public SakuUrlMapRecord() {
        super(SakuUrlMap.SAKU_URL_MAP);
    }

    /**
     * Create a detached, initialised SakuUrlMapRecord
     */
    public SakuUrlMapRecord(Long id, String lUrl, String sUrl, Timestamp createTime) {
        super(SakuUrlMap.SAKU_URL_MAP);

        set(0, id);
        set(1, lUrl);
        set(2, sUrl);
        set(3, createTime);
    }
}
