/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.siu.saku.jooq.tables.SakuPreRegister;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SakuPreRegisterRecord extends UpdatableRecordImpl<SakuPreRegisterRecord> implements Record4<Long, Long, Long, Timestamp> {

    private static final long serialVersionUID = -1016392098;

    /**
     * Setter for <code>ganxu.saku_pre_register.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ganxu.saku_pre_register.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ganxu.saku_pre_register.start_no</code>. 开始编号
     */
    public void setStartNo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ganxu.saku_pre_register.start_no</code>. 开始编号
     */
    public Long getStartNo() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ganxu.saku_pre_register.end_no</code>. 结束编号
     */
    public void setEndNo(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ganxu.saku_pre_register.end_no</code>. 结束编号
     */
    public Long getEndNo() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ganxu.saku_pre_register.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ganxu.saku_pre_register.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SakuPreRegister.SAKU_PRE_REGISTER.ID;
    }

    @Override
    public Field<Long> field2() {
        return SakuPreRegister.SAKU_PRE_REGISTER.START_NO;
    }

    @Override
    public Field<Long> field3() {
        return SakuPreRegister.SAKU_PRE_REGISTER.END_NO;
    }

    @Override
    public Field<Timestamp> field4() {
        return SakuPreRegister.SAKU_PRE_REGISTER.CREATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getStartNo();
    }

    @Override
    public Long component3() {
        return getEndNo();
    }

    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getStartNo();
    }

    @Override
    public Long value3() {
        return getEndNo();
    }

    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    @Override
    public SakuPreRegisterRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SakuPreRegisterRecord value2(Long value) {
        setStartNo(value);
        return this;
    }

    @Override
    public SakuPreRegisterRecord value3(Long value) {
        setEndNo(value);
        return this;
    }

    @Override
    public SakuPreRegisterRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SakuPreRegisterRecord values(Long value1, Long value2, Long value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SakuPreRegisterRecord
     */
    public SakuPreRegisterRecord() {
        super(SakuPreRegister.SAKU_PRE_REGISTER);
    }

    /**
     * Create a detached, initialised SakuPreRegisterRecord
     */
    public SakuPreRegisterRecord(Long id, Long startNo, Long endNo, Timestamp createTime) {
        super(SakuPreRegister.SAKU_PRE_REGISTER);

        set(0, id);
        set(1, startNo);
        set(2, endNo);
        set(3, createTime);
    }
}
