/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SakuPreRegister implements Serializable {

    private static final long serialVersionUID = 1213977618;

    private Long      id;
    private Long      startNo;
    private Long      endNo;
    private Timestamp createTime;

    public SakuPreRegister() {}

    public SakuPreRegister(SakuPreRegister value) {
        this.id = value.id;
        this.startNo = value.startNo;
        this.endNo = value.endNo;
        this.createTime = value.createTime;
    }

    public SakuPreRegister(
        Long      id,
        Long      startNo,
        Long      endNo,
        Timestamp createTime
    ) {
        this.id = id;
        this.startNo = startNo;
        this.endNo = endNo;
        this.createTime = createTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStartNo() {
        return this.startNo;
    }

    public void setStartNo(Long startNo) {
        this.startNo = startNo;
    }

    public Long getEndNo() {
        return this.endNo;
    }

    public void setEndNo(Long endNo) {
        this.endNo = endNo;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SakuPreRegister (");

        sb.append(id);
        sb.append(", ").append(startNo);
        sb.append(", ").append(endNo);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
