/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SakuShorturlMap implements Serializable {

    private static final long serialVersionUID = 51262489;

    private Long      id;
    private String    lUrl;
    private String    lUrlMd5;
    private Timestamp createTime;

    public SakuShorturlMap() {}

    public SakuShorturlMap(SakuShorturlMap value) {
        this.id = value.id;
        this.lUrl = value.lUrl;
        this.lUrlMd5 = value.lUrlMd5;
        this.createTime = value.createTime;
    }

    public SakuShorturlMap(
        Long      id,
        String    lUrl,
        String    lUrlMd5,
        Timestamp createTime
    ) {
        this.id = id;
        this.lUrl = lUrl;
        this.lUrlMd5 = lUrlMd5;
        this.createTime = createTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLUrl() {
        return this.lUrl;
    }

    public void setLUrl(String lUrl) {
        this.lUrl = lUrl;
    }

    public String getLUrlMd5() {
        return this.lUrlMd5;
    }

    public void setLUrlMd5(String lUrlMd5) {
        this.lUrlMd5 = lUrlMd5;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SakuShorturlMap (");

        sb.append(id);
        sb.append(", ").append(lUrl);
        sb.append(", ").append(lUrlMd5);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
