/*
 * This file is generated by jOOQ.
 */
package org.siu.saku.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SakuUrlMap implements Serializable {

    private static final long serialVersionUID = 1285394570;

    private Long      id;
    private String    lUrl;
    private String    sUrl;
    private Timestamp createTime;

    public SakuUrlMap() {}

    public SakuUrlMap(SakuUrlMap value) {
        this.id = value.id;
        this.lUrl = value.lUrl;
        this.sUrl = value.sUrl;
        this.createTime = value.createTime;
    }

    public SakuUrlMap(
        Long      id,
        String    lUrl,
        String    sUrl,
        Timestamp createTime
    ) {
        this.id = id;
        this.lUrl = lUrl;
        this.sUrl = sUrl;
        this.createTime = createTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLUrl() {
        return this.lUrl;
    }

    public void setLUrl(String lUrl) {
        this.lUrl = lUrl;
    }

    public String getSUrl() {
        return this.sUrl;
    }

    public void setSUrl(String sUrl) {
        this.sUrl = sUrl;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SakuUrlMap (");

        sb.append(id);
        sb.append(", ").append(lUrl);
        sb.append(", ").append(sUrl);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
